language: python
python:
    - "3.6"
# command to install dependencies
install:
    - pip install sc2reader
    - python setup.py develop
# command to run tests
script:
    - python tests/__main__.py
    - python tests/unit/__main__.py